#ifndef OKJVERSION_H
#define OKJVERSION_H

#define OKJ_VERSION_MAJOR 2
#define OKJ_VERSION_MINOR 2
#define OKJ_VERSION_BUILD 2
#define OKJ_VERSION_STRING "2.2.2"
#define OKJ_VERSION_BRANCH "unstable"

#endif //OKJVERSION_H
